language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - 7.0

install:
    - composer update --prefer-source

script:
  - php vendor/bin/phpunit
  - php vendor/bin/phpcs -n --standard=PSR1,PSR2 --report=full src/ tests

after_script:
   - wget https://scrutinizer-ci.com/ocular.phar
   - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover build/docs/clover.xml; fi;'
